import Link from 'next/link'
import { BookOpen, ChevronRight, Newspaper, School, Trophy, Users } from 'lucide-react'
import { prisma } from '@/lib/prisma'

export default async function AdminDashboard() {
  const [news, drafts, programs, achievements, staff, registration, recent] = await Promise.all([
    prisma.news.count({ where: { status: 'PUBLISHED' } }), prisma.news.count({ where: { status: 'DRAFT' } }), prisma.educationProgram.count({ where: { isActive: true } }), prisma.achievement.count({ where: { isActive: true } }), prisma.staff.count({ where: { isActive: true } }), prisma.registrationSettings.findUnique({ where: { id: 'main' } }), prisma.news.findMany({ take: 5, orderBy: { updatedAt: 'desc' }, select: { id: true, title: true, status: true, updatedAt: true } }),
  ])
  const stats = [{ name:'Berita Terbit',value:news,note:`${drafts} draf`,icon:Newspaper,color:'bg-purple-100 text-purple-700'},{name:'Program Aktif',value:programs,note:'Tampil di publik',icon:School,color:'bg-blue-100 text-blue-700'},{name:'Prestasi Aktif',value:achievements,note:'Tampil di publik',icon:Trophy,color:'bg-amber-100 text-amber-700'},{name:'Guru & Staf',value:staff,note:'Tampil di publik',icon:Users,color:'bg-emerald-100 text-emerald-700'}]
  const links=[['Tulis berita baru','/admin/berita/tambah'],['Tambah guru atau staf','/admin/guru/tambah'],['Ubah profil sekolah','/admin/tentang'],['Pengaturan PPDB','/admin/pendaftaran']]
  return <div className="space-y-6"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({name,value,note,icon:Icon,color})=><article key={name} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className={`inline-flex rounded-2xl p-3 ${color}`}><Icon size={25}/></span><p className="mt-4 text-4xl font-black text-slate-900">{value}</p><h2 className="mt-1 font-bold text-slate-700">{name}</h2><p className="mt-1 text-xs text-slate-400">{note}</p></article>)}</div><div className={`rounded-2xl border p-5 ${registration?.isOpen ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-white'}`}><div className="flex items-center gap-3"><BookOpen className="text-emerald-700"/><div><h2 className="font-bold text-slate-900">PPDB {registration?.isOpen ? 'sedang dibuka' : 'sedang ditutup'}</h2><p className="text-sm text-slate-600">{registration ? `${registration.academicYear} · ${registration.currentWave} · Kuota ${registration.quota}` : 'Pengaturan belum tersedia'}</p></div></div></div><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Konten terakhir diperbarui</h2><div className="mt-4 divide-y">{recent.map(item=><div key={item.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold text-slate-800">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.updatedAt.toLocaleDateString('id-ID',{dateStyle:'medium'})}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status==='PUBLISHED'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{item.status==='PUBLISHED'?'Terbit':'Draf'}</span></div>)}</div></section><section className="rounded-2xl bg-emerald-900 p-6 text-white"><h2 className="text-xl font-bold">Pintasan cepat</h2><div className="mt-5 space-y-3">{links.map(([label,href])=><Link key={href} href={href} className="flex items-center justify-between rounded-xl border border-emerald-700 bg-emerald-800/60 px-4 py-3 text-sm font-semibold hover:bg-amber-500 hover:text-emerald-950">{label}<ChevronRight size={17}/></Link>)}</div></section></div></div>
}
