import Image from 'next/image'
import { BookOpen, ShieldCheck, UserRound } from 'lucide-react'
import { Eyebrow, Hl } from '@/components/SharedUI'
import { getPublicStaff } from '@/lib/staff'

export default async function GuruPage(){const people=await getPublicStaff(),principal=people.find(x=>x.category==='PRINCIPAL'),teachers=people.filter(x=>x.category==='TEACHER'),staff=people.filter(x=>x.category==='STAFF');return <main>
  <section className="border-b border-emerald-100 bg-[#f4fcf7] py-20 text-center"><div className="container mx-auto max-w-3xl px-6"><Eyebrow>Tenaga Pendidik</Eyebrow><h1 className="text-4xl font-extrabold text-[#0a1c12] md:text-5xl">Guru &amp; <Hl>Staf</Hl></h1><p className="mt-5 leading-relaxed text-[#6b8077]">Mengenal tim yang mendampingi tumbuh kembang putra-putri dengan penuh perhatian dan profesionalisme.</p></div></section>
  {principal&&<section className="py-20"><div className="container mx-auto max-w-4xl px-6"><div className="grid items-center gap-8 overflow-hidden rounded-[2rem] bg-emerald-800 p-7 text-white md:grid-cols-[220px_1fr] md:p-10"><Photo item={principal}/><div><span className="text-xs font-bold uppercase tracking-widest text-emerald-200">Pimpinan Lembaga</span><h2 className="mt-3 text-3xl font-extrabold text-white">{principal.name}</h2><p className="mt-2 text-emerald-100">{principal.position}</p>{principal.education&&<p className="mt-5 text-sm font-semibold text-emerald-50">{principal.education}</p>}</div></div></div></section>}
  <PeopleSection title="Dewan Guru" icon={BookOpen} people={teachers}/><PeopleSection title="Staf & Tenaga Kependidikan" icon={ShieldCheck} people={staff}/>
  {!people.length&&<section className="py-24 text-center text-slate-500"><UserRound className="mx-auto mb-4 text-slate-300" size={56}/><p>Data guru dan staf sedang diperbarui.</p></section>}
</main>}

type Person=Awaited<ReturnType<typeof getPublicStaff>>[number]
function Photo({item}:{item:Person}){return <div className="relative mx-auto aspect-[3/4] w-full max-w-[220px] overflow-hidden rounded-2xl bg-white/10">{item.image?<Image src={item.image} alt={item.imageAlt||item.name} fill sizes="220px" className="object-cover"/>:<div className="absolute inset-0 flex items-center justify-center"><UserRound size={70} className="text-white/40"/></div>}</div>}
function PeopleSection({title,icon:Icon,people}:{title:string;icon:typeof BookOpen;people:Person[]}){if(!people.length)return null;return <section className="border-t border-slate-100 py-20"><div className="container mx-auto max-w-6xl px-6"><div className="mb-10 flex items-center gap-4"><span className="rounded-2xl bg-emerald-50 p-4 text-emerald-700"><Icon size={28}/></span><h2 className="text-3xl font-extrabold text-[#0a1c12]">{title}</h2></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{people.map(item=><article key={item.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><Photo item={item}/><div className="p-5"><h3 className="font-extrabold text-slate-900">{item.name}</h3><p className="mt-1 text-sm font-semibold text-emerald-700">{item.position}</p>{item.education&&<p className="mt-3 border-t pt-3 text-xs font-semibold text-slate-500">{item.education}</p>}</div></article>)}</div></div></section>}
