'use server'
import { getServerSession } from 'next-auth';import{revalidatePath}from'next/cache';import{redirect}from'next/navigation';import{mkdir,unlink,writeFile}from'node:fs/promises';import path from'node:path';import{authOptions}from'@/lib/auth';import{prisma}from'@/lib/prisma';
const text=(d:FormData,k:string)=>String(d.get(k)??'').trim();const req=(d:FormData,k:string,l:string)=>{const v=text(d,k);if(!v)throw new Error(`${l} wajib diisi.`);return v};async function admin(){if(!(await getServerSession(authOptions))?.user)throw new Error('Anda harus login sebagai admin.')}
async function save(file:File|null){if(!file||!file.size)return undefined;const ext=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}as Record<string,string>)[file.type];if(!ext)throw new Error('Gambar harus JPG, PNG, atau WebP.');if(file.size>5*1024*1024)throw new Error('Gambar maksimal 5 MB.');const dir=path.join(process.cwd(),'public','uploads','achievements');await mkdir(dir,{recursive:true});const name=`${Date.now()}-${crypto.randomUUID()}.${ext}`;await writeFile(path.join(dir,name),Buffer.from(await file.arrayBuffer()));return `/uploads/achievements/${name}`}
async function remove(file:string|null){if(!file?.startsWith('/uploads/achievements/'))return;const root=path.resolve(process.cwd(),'public','uploads','achievements'),target=path.resolve(process.cwd(),'public',file.slice(1));if(target.startsWith(`${root}${path.sep}`))await unlink(target).catch(()=>undefined)}
function values(d:FormData){const year=Number(text(d,'year'));if(!Number.isInteger(year)||year<1990||year>2100)throw new Error('Tahun prestasi tidak valid.');return{title:req(d,'title','Nama prestasi'),recipient:req(d,'recipient','Penerima'),category:req(d,'category','Kategori'),level:req(d,'level','Tingkat'),year,description:req(d,'description','Deskripsi'),imageAlt:text(d,'imageAlt')||null,active:d.get('isActive')==='on',featured:d.get('isFeatured')==='on',order:Number(text(d,'sortOrder'))||0}}
function refresh(){revalidatePath('/');revalidatePath('/prestasi');revalidatePath('/admin/prestasi')}
export async function createAchievement(d:FormData){await admin();const v=values(d),image=await save(d.get('image')as File|null),id=crypto.randomUUID();await prisma.$executeRaw`INSERT INTO Achievement(id,title,recipient,category,level,year,description,image,imageAlt,isActive,isFeatured,sortOrder,createdAt,updatedAt)VALUES(${id},${v.title},${v.recipient},${v.category},${v.level},${v.year},${v.description},${image||null},${v.imageAlt},${v.active},${v.featured},${v.order},NOW(3),NOW(3))`;refresh();redirect('/admin/prestasi?saved=1')}
export async function updateAchievement(id:string,d:FormData){await admin();const old=(await prisma.$queryRaw<Array<{image:string|null}>>`SELECT image FROM Achievement WHERE id=${id} LIMIT 1`)[0];if(!old)throw new Error('Prestasi tidak ditemukan.');const v=values(d),uploaded=await save(d.get('image')as File|null),removeRequested=d.get('removeImage')==='on',image=removeRequested?null:uploaded??old.image;await prisma.$executeRaw`UPDATE Achievement SET title=${v.title},recipient=${v.recipient},category=${v.category},level=${v.level},year=${v.year},description=${v.description},image=${image},imageAlt=${v.imageAlt},isActive=${v.active},isFeatured=${v.featured},sortOrder=${v.order},updatedAt=NOW(3) WHERE id=${id}`;if((uploaded||removeRequested)&&old.image)await remove(old.image);refresh();redirect('/admin/prestasi?saved=1')}
export async function deleteAchievement(id:string){await admin();const old=(await prisma.$queryRaw<Array<{image:string|null}>>`SELECT image FROM Achievement WHERE id=${id} LIMIT 1`)[0];if(old){await prisma.$executeRaw`DELETE FROM Achievement WHERE id=${id}`;await remove(old.image);refresh()}}
