'use server'
import { getServerSession } from 'next-auth'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { mkdir, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

const text = (d: FormData, k: string) => String(d.get(k) ?? '').trim()
const req = (d: FormData, k: string, l: string) => { const v = text(d, k); if (!v) throw new Error(`${l} wajib diisi.`); return v }
const slugify = (v: string) => v.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 80)
async function admin() { if (!(await getServerSession(authOptions))?.user) throw new Error('Anda harus login sebagai admin.') }
async function uniqueSlug(title: string, id?: string) { const base = slugify(title) || `program-${Date.now()}`; let slug = base, n = 2; while ((await prisma.$queryRaw<Array<{ id: string }>>`SELECT id FROM EducationProgram WHERE slug = ${slug} AND (${id || null} IS NULL OR id <> ${id || null}) LIMIT 1`).length) slug = `${base}-${n++}`; return slug }
async function image(file: File | null) { if (!file || !file.size) return undefined; const ext = ({ 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' } as Record<string,string>)[file.type]; if (!ext) throw new Error('Gambar harus JPG, PNG, atau WebP.'); if (file.size > 5*1024*1024) throw new Error('Gambar maksimal 5 MB.'); const dir = path.join(process.cwd(),'public','uploads','programs'); await mkdir(dir,{recursive:true}); const name=`${Date.now()}-${crypto.randomUUID()}.${ext}`; await writeFile(path.join(dir,name),Buffer.from(await file.arrayBuffer())); return `/uploads/programs/${name}` }
async function remove(file: string | null) { if (!file?.startsWith('/uploads/programs/')) return; const root=path.resolve(process.cwd(),'public','uploads','programs'), target=path.resolve(process.cwd(),'public',file.slice(1)); if(target.startsWith(`${root}${path.sep}`)) await unlink(target).catch(()=>undefined) }
function values(d: FormData) { const highlights=text(d,'highlights').split(/\r?\n/).map(v=>v.replace(/^[-•]\s*/,'').trim()).filter(Boolean); if(!highlights.length) throw new Error('Minimal satu fokus program wajib diisi.'); return { title:req(d,'title','Nama program'), eyebrow:req(d,'eyebrow','Label program'), description:req(d,'description','Deskripsi'), age:req(d,'age','Kelompok usia'), schedule:req(d,'schedule','Jadwal'), capacity:req(d,'capacity','Kapasitas'), ratio:req(d,'teacherRatio','Rasio guru'), highlights:JSON.stringify(highlights), active:d.get('isActive')==='on', featured:d.get('isFeatured')==='on', order:Number(text(d,'sortOrder'))||0 } }
function refresh() { revalidatePath('/'); revalidatePath('/program'); revalidatePath('/admin/program') }
export async function createProgram(d: FormData) { await admin(); const v=values(d), saved=await image(d.get('image') as File|null), id=crypto.randomUUID(), slug=await uniqueSlug(v.title); await prisma.$executeRaw`INSERT INTO EducationProgram (id,slug,title,eyebrow,description,age,schedule,capacity,teacherRatio,highlights,image,isActive,isFeatured,sortOrder,createdAt,updatedAt) VALUES (${id},${slug},${v.title},${v.eyebrow},${v.description},${v.age},${v.schedule},${v.capacity},${v.ratio},${v.highlights},${saved||null},${v.active},${v.featured},${v.order},NOW(3),NOW(3))`; refresh(); redirect('/admin/program?saved=1') }
export async function updateProgram(id:string,d:FormData) { await admin(); const old=(await prisma.$queryRaw<Array<{image:string|null;slug:string;title:string}>>`SELECT image,slug,title FROM EducationProgram WHERE id=${id} LIMIT 1`)[0]; if(!old) throw new Error('Program tidak ditemukan.'); const v=values(d), saved=await image(d.get('image') as File|null), removeRequested=d.get('removeImage')==='on', slug=v.title===old.title?old.slug:await uniqueSlug(v.title,id), finalImage=removeRequested?null:saved??old.image; await prisma.$executeRaw`UPDATE EducationProgram SET slug=${slug},title=${v.title},eyebrow=${v.eyebrow},description=${v.description},age=${v.age},schedule=${v.schedule},capacity=${v.capacity},teacherRatio=${v.ratio},highlights=${v.highlights},image=${finalImage},isActive=${v.active},isFeatured=${v.featured},sortOrder=${v.order},updatedAt=NOW(3) WHERE id=${id}`; if((saved||removeRequested)&&old.image) await remove(old.image); refresh(); revalidatePath(`/program/${old.slug}`); revalidatePath(`/program/${slug}`); redirect('/admin/program?saved=1') }
export async function deleteProgram(id:string) { await admin(); const old=(await prisma.$queryRaw<Array<{image:string|null;slug:string}>>`SELECT image,slug FROM EducationProgram WHERE id=${id} LIMIT 1`)[0]; if(old){await prisma.$executeRaw`DELETE FROM EducationProgram WHERE id=${id}`;await remove(old.image);refresh();revalidatePath(`/program/${old.slug}`)} }
