import { getServerSession } from 'next-auth'
import { CheckCircle2, Lock, Save, User } from 'lucide-react'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { changePassword, updateProfile } from './actions'

const field = 'w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-emerald-500'
export default async function AdminProfil({ searchParams }: PageProps<'/admin/profil'>) {
  const [session, query] = await Promise.all([getServerSession(authOptions), searchParams]); const user = await prisma.user.findUniqueOrThrow({ where: { email: session!.user!.email! } }); const security = query.tab === 'pengaturan'
  return <div className="space-y-6">
    {query.saved && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800"><CheckCircle2 size={18}/>{query.saved === 'password' ? 'Password berhasil diperbarui.' : 'Profil berhasil diperbarui. Silakan login ulang jika email berubah.'}</div>}
    <div className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-3"><a href="/admin/profil" className={`flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${!security ? 'bg-emerald-100 text-emerald-800' : 'text-slate-600'}`}><User size={18}/>Informasi Profil</a><a href="/admin/profil?tab=pengaturan" className={`flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${security ? 'bg-amber-100 text-amber-800' : 'text-slate-600'}`}><Lock size={18}/>Ganti Password</a></div>
    {!security ? <form action={updateProfile} className="max-w-3xl space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><h2 className="text-xl font-bold">Profil administrator</h2><label className="block text-sm font-semibold">Nama lengkap<input name="name" defaultValue={user.name ?? ''} className={`${field} mt-2`} required/></label><label className="block text-sm font-semibold">Email login<input name="email" type="email" defaultValue={user.email} className={`${field} mt-2`} required/></label><div className="flex justify-end border-t pt-5"><button className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-5 py-3 text-sm font-bold text-emerald-950"><Save size={18}/>Simpan Profil</button></div></form> : <form action={changePassword} className="max-w-3xl space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><h2 className="text-xl font-bold">Keamanan akun</h2><label className="block text-sm font-semibold">Password saat ini<input name="currentPassword" type="password" className={`${field} mt-2`} required/></label><label className="block text-sm font-semibold">Password baru<input name="password" type="password" minLength={8} className={`${field} mt-2`} required/></label><label className="block text-sm font-semibold">Konfirmasi password baru<input name="confirmation" type="password" minLength={8} className={`${field} mt-2`} required/></label><div className="flex justify-end border-t pt-5"><button className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white"><Save size={18}/>Perbarui Password</button></div></form>}
  </div>
}
