import { prisma } from '@/lib/prisma'
export type SchoolProfileData={pageTitle:string;introduction:string;principalName:string;principalPhoto:string;welcomeMessage:string;npsn:string;accreditation:string;foundedYear:string;operationalPermit:string;permitIssuer:string}
export type Milestone={year:string;title:string;description:string}
export type SchoolHistoryData={pageTitle:string;introduction:string;storyTitle:string;story:string;image:string;milestones:Milestone[]}
export type FacilityItem={title:string;description:string;image:string;icon:string;isActive:boolean}
export type FacilityData={pageTitle:string;introduction:string;facilities:FacilityItem[]}
export const DEFAULT_PROFILE:SchoolProfileData={pageTitle:'Profil Sekolah',introduction:'Membangun generasi cerdas, kreatif, dan berakhlak mulia melalui pendidikan usia dini yang menyenangkan dan berlandaskan nilai-nilai keislaman.',principalName:'Hj. Siti Aminah, S.Pd.',principalPhoto:'',welcomeMessage:`Assalamu’alaikum Warahmatullahi Wabarakatuh.\n\nPuji syukur ke hadirat Allah SWT. TK ABA 8 Kepanjen berkomitmen menyediakan lingkungan belajar yang aman, inspiratif, dan penuh kasih sayang pada masa emas tumbuh kembang anak.\n\nSemoga sekolah dan keluarga dapat terus berjalan bersama dalam mendampingi anak menjadi pribadi yang mandiri, percaya diri, dan berakhlak mulia.`,npsn:'20500123',accreditation:'Swasta / Terakreditasi A',foundedYear:'2005',operationalPermit:'421.1/123/DIKNAS/2005',permitIssuer:'Dinas Pendidikan Kabupaten Malang'}
export const DEFAULT_HISTORY:SchoolHistoryData={pageTitle:'Sejarah Perjalanan',introduction:'Jejak dedikasi TK ABA 8 Kepanjen dalam menghadirkan pendidikan anak usia dini yang bermutu.',storyTitle:'Lahir dari Kepedulian',story:'Berawal dari kebutuhan masyarakat Kepanjen akan pendidikan anak usia dini yang memadukan perkembangan anak dan penanaman akhlak Islami, Aisyiyah cabang Kepanjen mendirikan TK ABA 8. Meski dimulai dengan keterbatasan, semangat memberikan pendidikan terbaik terus bertumbuh.',image:'',milestones:[{year:'2005',title:'Awal Berdiri',description:'Sekolah resmi didirikan atas inisiatif pengurus Aisyiyah dan tokoh masyarakat setempat.'},{year:'2010',title:'Pembangunan Gedung Baru',description:'Dukungan wali murid dan donatur membantu sekolah menghadirkan ruang belajar yang lebih layak.'},{year:'2015',title:'Meraih Akreditasi A',description:'Peningkatan mutu layanan dan fasilitas mengantarkan sekolah meraih akreditasi A.'},{year:'2018',title:'Kurikulum Berbasis Karakter',description:'Kurikulum nasional diperkaya pembelajaran sentra dan pembiasaan karakter Islami.'},{year:'2023',title:'Sekolah Ramah Anak',description:'Sekolah memperoleh apresiasi atas lingkungan belajar yang aman, inklusif, dan menyenangkan.'}]}
export const DEFAULT_FACILITIES:FacilityData={pageTitle:'Fasilitas Sekolah',introduction:'Lingkungan yang aman, bersih, dan mendukung anak bereksplorasi sambil belajar.',facilities:[['Ruang Kelas Nyaman & Interaktif','Ruang belajar dengan pencahayaan baik, alat permainan edukatif, dan loker pribadi.','BookOpen'],['Taman Bermain Outdoor','Area bermain luar ruang untuk melatih motorik, keberanian, dan interaksi sosial.','Trees'],['Ruang Sentra Kreativitas','Ruang eksplorasi seni, bermain peran, konstruksi, dan berbagai proyek anak.','Palette'],['Perpustakaan Mini','Koleksi bacaan anak yang menumbuhkan rasa ingin tahu dan kecintaan membaca.','Library'],['Unit Kesehatan Sekolah','Ruang pertolongan pertama dan pemantauan kesehatan dasar siswa.','HeartPulse'],['Media Audio Visual','Perangkat pendukung pembelajaran melalui video, musik, dan materi interaktif.','MonitorPlay']].map(([title,description,icon])=>({title,description,image:'',icon,isActive:true}))}
const arr=<T>(v:unknown,f:T[])=>{try{const p=typeof v==='string'?JSON.parse(v):v;return Array.isArray(p)?p as T[]:f}catch{return f}}
export async function getSchoolProfile(){const x=await prisma.$queryRaw<Array<Omit<SchoolProfileData,'principalPhoto'>&{principalPhoto:string|null}>>`SELECT pageTitle,introduction,principalName,principalPhoto,welcomeMessage,npsn,accreditation,foundedYear,operationalPermit,permitIssuer FROM SchoolProfile WHERE id='main' LIMIT 1`.catch(()=>[]);return x[0]?{...x[0],principalPhoto:x[0].principalPhoto||''}:DEFAULT_PROFILE}
export async function getSchoolHistory(){const x=await prisma.$queryRaw<Array<Omit<SchoolHistoryData,'image'|'milestones'>&{image:string|null;milestones:unknown}>>`SELECT pageTitle,introduction,storyTitle,story,image,milestones FROM SchoolHistory WHERE id='main' LIMIT 1`.catch(()=>[]);return x[0]?{...x[0],image:x[0].image||'',milestones:arr(x[0].milestones,DEFAULT_HISTORY.milestones)}:DEFAULT_HISTORY}
export async function getFacilities(){const x=await prisma.$queryRaw<Array<Omit<FacilityData,'facilities'>&{facilities:unknown}>>`SELECT pageTitle,introduction,facilities FROM FacilitySettings WHERE id='main' LIMIT 1`.catch(()=>[]);return x[0]?{...x[0],facilities:arr(x[0].facilities,DEFAULT_FACILITIES.facilities)}:DEFAULT_FACILITIES}
