'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { parseJsonList,removeUpload,requireAdmin,requiredText,saveUpload } from '@/lib/admin-utils'
import type { FacilityItem } from '@/lib/school-about'
const imageTypes={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}
const done=(tab:string)=>{revalidatePath('/tentang/profil');revalidatePath('/tentang/sejarah');revalidatePath('/tentang/fasilitas');revalidatePath('/tentang');revalidatePath('/admin/tentang');redirect(`/admin/tentang?saved=${tab}`)}

export async function saveProfile(d:FormData){await requireAdmin();const old=await prisma.schoolProfile.findUnique({where:{id:'main'}}),uploaded=await saveUpload(d,{folder:'profile',field:'principalPhoto',types:imageTypes,maxMb:5}),remove=d.get('removePrincipalPhoto')==='on',photo=remove?null:uploaded??old?.principalPhoto??null;await prisma.schoolProfile.upsert({where:{id:'main'},create:{id:'main',pageTitle:requiredText(d,'pageTitle','Judul halaman'),introduction:requiredText(d,'introduction','Pengantar'),principalName:requiredText(d,'principalName','Nama kepala sekolah'),principalPhoto:photo,welcomeMessage:requiredText(d,'welcomeMessage','Sambutan'),npsn:requiredText(d,'npsn','NPSN'),accreditation:requiredText(d,'accreditation','Status / akreditasi'),foundedYear:requiredText(d,'foundedYear','Tahun berdiri'),operationalPermit:requiredText(d,'operationalPermit','Izin operasional'),permitIssuer:requiredText(d,'permitIssuer','Penerbit izin')},update:{pageTitle:requiredText(d,'pageTitle','Judul halaman'),introduction:requiredText(d,'introduction','Pengantar'),principalName:requiredText(d,'principalName','Nama kepala sekolah'),principalPhoto:photo,welcomeMessage:requiredText(d,'welcomeMessage','Sambutan'),npsn:requiredText(d,'npsn','NPSN'),accreditation:requiredText(d,'accreditation','Status / akreditasi'),foundedYear:requiredText(d,'foundedYear','Tahun berdiri'),operationalPermit:requiredText(d,'operationalPermit','Izin operasional'),permitIssuer:requiredText(d,'permitIssuer','Penerbit izin')}});if((uploaded||remove)&&old?.principalPhoto)await removeUpload(old.principalPhoto,'profile');done('profil')}

export async function saveHistory(d:FormData){await requireAdmin();const milestones=parseJsonList(d,'milestones','Tonggak sejarah',(raw,i)=>{const x=raw as Record<string,unknown>,year=String(x.year??'').trim(),title=String(x.title??'').trim(),description=String(x.description??'').trim();if(!year||!title||!description)throw new Error(`Tonggak ${i+1} belum lengkap.`);return{year,title,description}}),old=await prisma.schoolHistory.findUnique({where:{id:'main'}}),uploaded=await saveUpload(d,{folder:'history',field:'historyImage',types:imageTypes,maxMb:5}),remove=d.get('removeHistoryImage')==='on',image=remove?null:uploaded??old?.image??null;await prisma.schoolHistory.upsert({where:{id:'main'},create:{id:'main',pageTitle:requiredText(d,'historyPageTitle','Judul halaman'),introduction:requiredText(d,'historyIntroduction','Pengantar'),storyTitle:requiredText(d,'storyTitle','Judul cerita'),story:requiredText(d,'story','Cerita sejarah'),image,milestones},update:{pageTitle:requiredText(d,'historyPageTitle','Judul halaman'),introduction:requiredText(d,'historyIntroduction','Pengantar'),storyTitle:requiredText(d,'storyTitle','Judul cerita'),story:requiredText(d,'story','Cerita sejarah'),image,milestones}});if((uploaded||remove)&&old?.image)await removeUpload(old.image,'history');done('sejarah')}

type FacilityPayload=FacilityItem&{clientKey:string}
export async function saveFacilities(d:FormData){await requireAdmin();const raw=parseJsonList(d,'facilities','Fasilitas',(value,i)=>{const x=value as Record<string,unknown>,title=String(x.title??'').trim(),description=String(x.description??'').trim(),clientKey=String(x.clientKey??'').trim();if(!clientKey||!title||!description)throw new Error(`Fasilitas ${i+1} belum lengkap.`);return{clientKey,title,description,image:String(x.image??'').trim(),icon:String(x.icon??'Building2'),isActive:Boolean(x.isActive)}}),old=await prisma.facilitySettings.findUnique({where:{id:'main'}}),oldItems=Array.isArray(old?.facilities)?old.facilities as unknown as FacilityItem[]:[],facilities:FacilityItem[]=[];for(const item of raw as FacilityPayload[]){const uploaded=await saveUpload(d,{folder:'facilities',field:`facilityImage_${item.clientKey}`,types:imageTypes,maxMb:5}),remove=d.get(`removeFacilityImage_${item.clientKey}`)==='on';facilities.push({title:item.title,description:item.description,image:remove?'':uploaded??item.image,icon:item.icon,isActive:item.isActive})}await prisma.facilitySettings.upsert({where:{id:'main'},create:{id:'main',pageTitle:requiredText(d,'facilityPageTitle','Judul halaman'),introduction:requiredText(d,'facilityIntroduction','Pengantar'),facilities},update:{pageTitle:requiredText(d,'facilityPageTitle','Judul halaman'),introduction:requiredText(d,'facilityIntroduction','Pengantar'),facilities}});const retained=new Set(facilities.map(x=>x.image).filter(Boolean));for(const item of oldItems)if(item.image&&!retained.has(item.image))await removeUpload(item.image,'facilities');done('fasilitas')}
