'use client'
import { useState } from 'react'
import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react'

type Item=Record<string,string|boolean>
type Field={key:string;label:string;kind?:'text'|'textarea'|'select'|'checkbox';placeholder?:string;options?:string[]}
export default function DynamicListEditor({name,label,initial,fields,newItem,min=0,max}:{name:string;label:string;initial:Item[];fields:Field[];newItem:Item;min?:number;max?:number}){
 const[items,setItems]=useState<Item[]>(initial)
 const update=(index:number,key:string,value:string|boolean)=>setItems(list=>list.map((item,i)=>i===index?{...item,[key]:value}:item))
 const move=(index:number,to:number)=>setItems(list=>{if(to<0||to>=list.length)return list;const copy=[...list];[copy[index],copy[to]]=[copy[to],copy[index]];return copy})
 return <section className="space-y-4"><input type="hidden" name={name} value={JSON.stringify(items)}/><div className="flex items-center justify-between"><div><h3 className="font-bold text-slate-900">{label}</h3><p className="text-xs text-slate-500">Urutan kartu sama dengan urutan tampilan publik.</p></div><button type="button" disabled={max!==undefined&&items.length>=max} onClick={()=>setItems(list=>[...list,{...newItem}])} className="inline-flex items-center gap-2 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 disabled:cursor-not-allowed disabled:opacity-50"><Plus size={15}/>Tambah</button></div>
 {items.length===0&&<div className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-400">Belum ada item. Klik Tambah untuk membuat item.</div>}
 <div className="space-y-3">{items.map((item,index)=><div key={index} className="rounded-xl border border-slate-200 bg-slate-50/50 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-extrabold text-emerald-700">Item {index+1}</span><div className="flex gap-1"><button type="button" aria-label="Naik" disabled={index===0} onClick={()=>move(index,index-1)} className="rounded p-2 hover:bg-white disabled:opacity-25"><ArrowUp size={15}/></button><button type="button" aria-label="Turun" disabled={index===items.length-1} onClick={()=>move(index,index+1)} className="rounded p-2 hover:bg-white disabled:opacity-25"><ArrowDown size={15}/></button><button type="button" aria-label="Hapus" disabled={items.length<=min} onClick={()=>setItems(list=>list.filter((_,i)=>i!==index))} className="rounded p-2 text-red-600 hover:bg-red-50 disabled:opacity-25"><Trash2 size={15}/></button></div></div><div className="grid gap-3 md:grid-cols-2">{fields.map(field=><label key={field.key} className={field.kind==='textarea'?'md:col-span-2':'block'}><span className="mb-1 block text-xs font-semibold text-slate-600">{field.label}</span>{field.kind==='textarea'?<textarea rows={3} value={String(item[field.key]??'')} onChange={e=>update(index,field.key,e.target.value)} placeholder={field.placeholder} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/>:field.kind==='select'?<select value={String(item[field.key]??'')} onChange={e=>update(index,field.key,e.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm">{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.kind==='checkbox'?<input type="checkbox" checked={Boolean(item[field.key])} onChange={e=>update(index,field.key,e.target.checked)} className="h-5 w-5 accent-emerald-600"/>:<input value={String(item[field.key]??'')} onChange={e=>update(index,field.key,e.target.value)} placeholder={field.placeholder} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/>}</label>)}</div></div>)}</div></section>
}
