import type {Metadata} from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Calendar, ImageIcon, Search } from 'lucide-react'
import { formatNewsDate, searchPublishedNews } from '@/lib/news'
import { getSiteSettings } from '@/lib/site-settings'

export async function generateMetadata():Promise<Metadata>{const site=await getSiteSettings();return{title:'Berita',description:`Berita, pengumuman, kegiatan, dan kabar terbaru ${site.shortName}.`}}
export default async function BeritaPage({searchParams}:{searchParams:Promise<{q?:string;category?:string;year?:string;page?:string}>}){const raw=await searchParams,q=String(raw.q||'').trim().slice(0,100),category=String(raw.category||'').trim().slice(0,80),year=/^\d{4}$/.test(String(raw.year||''))?Number(raw.year):undefined,page=Math.max(1,Number(raw.page)||1);const[results,site]=await Promise.all([searchPublishedNews({query:q,category,year,page,pageSize:10}),getSiteSettings()]);const href=(next:number)=>{const params=new URLSearchParams();if(q)params.set('q',q);if(category)params.set('category',category);if(year)params.set('year',String(year));params.set('page',String(next));return`/berita?${params}`};return <main className="min-h-screen bg-[#f6faf8]">
  <section className="bg-[#073b20] py-20 text-white"><div className="container mx-auto px-6"><span className="text-xs font-bold uppercase tracking-[.2em] text-emerald-200">Kabar Sekolah</span><h1 className="mt-3 text-4xl font-extrabold text-white md:text-5xl">Berita &amp; Pengumuman</h1><p className="mt-4 max-w-xl leading-relaxed text-emerald-50">Ikuti kegiatan, prestasi, pengumuman, dan cerita terbaru dari keluarga besar {site.shortName}.</p></div></section>
  <section className="container mx-auto max-w-6xl px-6 py-14"><form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_190px_150px_auto]"><label className="relative"><span className="sr-only">Cari berita</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input name="q" defaultValue={q} placeholder="Cari judul atau ringkasan..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-4 text-sm text-slate-900 outline-none focus:border-emerald-500"/></label><select name="category" defaultValue={category} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none focus:border-emerald-500"><option value="">Semua kategori</option>{results.facets.categories.map(x=><option key={x}>{x}</option>)}</select><select name="year" defaultValue={year||''} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none focus:border-emerald-500"><option value="">Semua tahun</option>{results.facets.years.map(x=><option key={x}>{x}</option>)}</select><button className="rounded-xl bg-emerald-700 px-6 py-3 text-sm font-bold text-white">Terapkan</button></form>
  {(q||category||year)&&<div className="mt-4 flex items-center justify-between text-sm text-slate-600"><span>{results.total} hasil ditemukan</span><Link href="/berita" className="font-bold text-emerald-700">Reset filter</Link></div>}
  {results.items.length?<div className="mt-8 divide-y divide-slate-200 overflow-hidden rounded-2xl border border-slate-200 bg-white">{results.items.map((item,i)=><article key={item.id} className="grid gap-5 p-5 transition hover:bg-emerald-50/40 sm:grid-cols-[180px_1fr] md:p-6"><Link href={`/berita/${item.slug}`} className="relative aspect-[16/10] overflow-hidden rounded-xl bg-emerald-50 sm:aspect-auto sm:min-h-32">{item.image?<Image src={item.image} alt={item.imageAlt||item.title} fill priority={i<2} sizes="180px" className="object-cover"/>:<span className="absolute inset-0 flex items-center justify-center text-emerald-200"><ImageIcon size={36}/></span>}</Link><div className="min-w-0"><div className="flex flex-wrap items-center gap-3 text-xs font-semibold text-slate-500"><span className="rounded-full bg-emerald-50 px-3 py-1 text-emerald-700">{item.category}</span>{item.publishedAt&&<span className="flex items-center gap-1.5"><Calendar size={14}/>{formatNewsDate(item.publishedAt)}</span>}</div><h2 className="mt-3 text-xl font-extrabold leading-snug text-slate-900"><Link href={`/berita/${item.slug}`} className="hover:text-emerald-700">{item.title}</Link></h2>{item.excerpt&&<p className="mt-2 line-clamp-2 text-sm leading-relaxed text-slate-600">{item.excerpt}</p>}<Link href={`/berita/${item.slug}`} className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Baca selengkapnya<ArrowRight size={15}/></Link></div></article>)}</div>:<div className="mt-8 rounded-2xl border border-slate-200 bg-white py-20 text-center"><h2 className="text-xl font-bold text-slate-900">Berita tidak ditemukan</h2><p className="mt-2 text-sm text-slate-500">Coba ubah kata pencarian atau filter.</p></div>}
  {results.totalPages>1&&<nav aria-label="Pagination berita" className="mt-8 flex items-center justify-center gap-3"><Link aria-disabled={results.page<=1} href={results.page<=1?'#':href(results.page-1)} className={`rounded-xl border px-4 py-2 text-sm font-bold ${results.page<=1?'pointer-events-none text-slate-300':'bg-white text-slate-700'}`}>Sebelumnya</Link><span className="text-sm text-slate-500">Halaman {results.page} dari {results.totalPages}</span><Link aria-disabled={results.page>=results.totalPages} href={results.page>=results.totalPages?'#':href(results.page+1)} className={`rounded-xl border px-4 py-2 text-sm font-bold ${results.page>=results.totalPages?'pointer-events-none text-slate-300':'bg-white text-slate-700'}`}>Berikutnya</Link></nav>}
  </section>
</main>}
